### ISSUE TITLE
dockerfile 中的ntp 所依赖的tzdata 在安装时存在交互。会使docker build 暂停

### ISSUE THREAD

**Issue by LJNjust** [tikazyq/crawlab#11]

**Comment by tikazyq** [comment]
`apt-get install -y python3 python3-pip net-tools iputils-ping vim ntp`

加了`-y`参数应该不会才对

**Comment by tikazyq** [comment]
是否可以发日志？

**Comment by LJNjust** [comment]
然而我并没有保存日志，但是我可以把修改后的Dockerfile提供给你。见附件。只要添加一个环境变量即可。另外requirements.txt应该放在Dockerfile同级文件夹下。否则会在pip安装依赖是产生问题。
[Dockerfile.txt](https://github.com/tikazyq/crawlab/files/3037703/Dockerfile.txt)

**Comment by LJNjust** [comment]
> 是否可以发日志？



> 是否可以发日志？

然而我并没有保存日志，但是我可以把修改后的Dockerfile提供给你。见附件。只要添加一个环境变量即可。另外requirements.txt应该放在Dockerfile同级文件夹下。否则会在pip安装依赖是产生问题。
[Dockerfile.txt](https://github.com/tikazyq/crawlab/files/3037703/Dockerfile.txt)

**Comment by LJNjust** [comment]
> `apt-get install -y python3 python3-pip net-tools iputils-ping vim ntp`
> 
> 加了`-y`参数应该不会才对

然而我并没有保存日志，但是我可以把修改后的Dockerfile提供给你。见附件。只要添加一个环境变量即可。另外requirements.txt应该放在Dockerfile同级文件夹下。否则会在pip安装依赖是产生问题。
[Dockerfile.txt](https://github.com/tikazyq/crawlab/files/3037703/Dockerfile.txt)

**Comment by tikazyq** [comment]
感谢分享，下一版会考虑将该dockerfile整合进来

**Comment by tikazyq** [comment]
已修复
