### ISSUE TITLE
redis端口密码问题

### ISSUE THREAD

**Issue by 1941198** [tikazyq/crawlab#111]
docker run 时不能指定端口，CRAWLAB_REDIS_ADDRESS=127.0.0.1:6378 无效，链接时同样会访问127.0.0.1:6378:6379, 也不能指定密码，mongo一样。

**Comment by tikazyq** [comment]
参考这个文档，https://tikazyq.github.io/crawlab-docs/Config/

`CRAWLAB_REDIS_ADDRESS`不用指定端口，密码用`CRAWLAB_REDIS_PASSWORD`，mongo用`CRAWLAB_MONGO_USERNAME`、`CRAWLAB_MONGO_PASSWORD`
