### ISSUE TITLE
爬虫详情修改问题

### ISSUE THREAD

**Issue by 1941198** [tikazyq/crawlab#112]
第一次点击到 网站 那个input，没有数据时 白色的模态框 会一直显示，覆盖了运行与保存。

**Comment by tikazyq** [comment]
哪个版本，截个图看看呢

**Comment by 1941198** [comment]
最新的版本，线上的测试demo也是一样的
![image](https://user-images.githubusercontent.com/23349319/62448728-07c9f280-b79b-11e9-8579-cd65e678e4cd.png)

线上测试访问页面老是出现403.

**Comment by tikazyq** [comment]
确实是个bug，需要移除网站这个字段

**Comment by tikazyq** [comment]
fixed，在develop上
