### ISSUE TITLE
现在是不支持 直接部署了吗？

### ISSUE THREAD

**Issue by spidercamel** [tikazyq/crawlab#113]
crawlweb/crawlweb 不存在了。
docker部署步骤如果能详细点就好了

**Comment by tikazyq** [comment]
参考 https://tikazyq.github.io/crawlab-docs/Installation/Direct.html，直接部署还是支持的，只是之前的python换为了golang，因此crawlab/crawlab文件夹移除了。不过强烈建议用Docker来部署，这是最方便的方法了。有问题可以在交流群里提出来
