### ISSUE TITLE
上传的zip无法同步子节点

### ISSUE THREAD

**Issue by 1941198** [tikazyq/crawlab#114]
docker run -d --name crawlab_w1 -e CRAWLAB_REDIS_ADDRESS=redis -e CRAWLAB_MONGO_HOST=mongo -e CRAWLAB_SERVER_MASTER=N -e CRAWLAB_API_ADDRESS=192.168.2.222:8000 -e CRAWLAB_SPIDER_PATH=/app/spiders -v /var/logs/crawlab:/var/logs/crawlab --link mongo:mongo --link redis:redis --privileged=true tikazyq/crawlab

该docker显示已经上线
![image](https://user-images.githubusercontent.com/23349319/62508956-04d30e80-b83c-11e9-958e-9aaeb5b15c8f.png)
上传一个zip文件， 只包含一个test.js，console.log("test");
只有主节点可以运行，今天试了上传几次子节点依然没有，发现子节点报以下错误，进入docker中也没有目录建立，只有示例的目录。
![image](https://user-images.githubusercontent.com/23349319/62508967-0e5c7680-b83c-11e9-8d6a-ad61efad4277.png)

**Comment by tikazyq** [comment]
检查了日志有不有报错？按道理每60秒主节点会同步一次爬虫文件，这时候如果同步不成功应该有报错

`docker logs crawlab`
