### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by anye88** [tikazyq/crawlab#131]
request.js:22 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at request.js:22

**Comment by tikazyq** [comment]
可以再详细一点么

**Comment by anye88** [comment]
您好，我在用docker-compose运行起服务后，访问http://localhost:8080，以默认用户名密码admin登陆时，接口pending一段时间后报错，后台没有看到具体的报错信息，只在console看到一些报错信息。 if (error.response.status === 401) 

xhr.js:178 POST http://localhost:8000/login net::ERR_CONNECTION_REFUSED

request.js:22 Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at request.js:22

      .catch(error => {
        console.log(error)
        if (error.response.status === 401) {
          router.push('/login')
        }
        reject(error)
      })
  })

**Comment by tikazyq** [comment]
是不是CRAWLAB_API_ADDRESS没有设置呢，打开f12 network看看请求地址

**Comment by anye88** [comment]
CRAWLAB_API_ADDRESS怎设置，我直接使用docker-compose up 运行，这是f12看到的http://localhost:8000/login，我直接访问的话，提示404 page not found

**Comment by tikazyq** [comment]
请参考 https://tikazyq.github.io/crawlab-docs/QA/

**Comment by anye88** [comment]
非常感谢，在docker-compose.yml里的CRAWLAB_API_ADDRESS，把原来的localhost改为自己机器的ip，可以正常访问了

**Comment by anye88** [comment]
您好，能请教下您这个项目的架构设计吗？对了，我在点击定时任务，选择cron时，由于现在没有可选项，导致下拉菜单一直卡在那，退不出去，这个可能是前端的一个bug。

**Comment by tikazyq** [comment]
请另外提一个bug issue，并附上截图
