### ISSUE TITLE
Serious bugs about “CRAWLAB_SPIDER_PATH”

### ISSUE THREAD

**Issue by Zerorigin** [tikazyq/crawlab#150]
上传巨型爬虫项目压缩文件(如包含未经清理的 data/logs 等其它项目无关大文件)至 Crawlab 服务端或将 CRAWLAB_SPIDER_PATH 目录映射到宿主本地大文件目录时，会导致 Crawlab 容器异常占用内存，并持续读写硬盘直至宿主机内存被撑爆(如果未在使用 docker 部署时限制内存使用上限的话 )。负面影响，严重影响宿主机性能，造成宿主长时间无法正常提供其它服务(如SSH远程会话等)。
　
P.S：项目组说提个 issue 方便追踪，所以就随便写写了。

**Comment by tikazyq** [comment]
fixed in https://github.com/tikazyq/crawlab/pull/151
