### ISSUE TITLE
没有部署节点的方法吗.

### ISSUE THREAD

**Issue by klren0312** [tikazyq/crawlab#152]
文档里没看到

**Comment by tikazyq** [comment]
crawlab是自动部署爬虫的，请看这个文档 https://tikazyq.github.io/crawlab-docs/Usage/Spider/Deploy.html

**Comment by klren0312** [comment]
我说子节点是怎么部署的...

**Comment by tikazyq** [comment]
可以参考文档中的docker来部署，如果实在有不清楚的可以加微信tikazyq1答疑

**Comment by klren0312** [comment]
你的意思是 子节点也是要和主节点一样布个全套

**Comment by tikazyq** [comment]
是的
