### ISSUE TITLE
执行 python3 ./bin/run_flower.py 报以下错误

### ISSUE THREAD

**Issue by cheneystar** [tikazyq/crawlab#16]
[I 190409 17:22:40 command:147] Registered tasks:

    ['celery.accumulate',

     'celery.backend_cleanup',

     'celery.chain',

     'celery.chord',

     'celery.chord_unlock',

     'celery.chunks',

     'celery.group',

     'celery.map',

     'celery.starmap']

[I 190409 17:22:40 mixins:229] Connected to redis://127.0.0.1:6379/0

[W 190409 17:22:45 control:44] 'stats' inspect method failed

[W 190409 17:22:45 control:44] 'active_queues' inspect method failed

[W 190409 17:22:45 control:44] 'registered' inspect method failed

[W 190409 17:22:45 control:44] 'scheduled' inspect method failed

[W 190409 17:22:45 control:44] 'active' inspect method failed

[W 190409 17:22:45 control:44] 'reserved' inspect method failed

[W 190409 17:22:45 control:44] 'revoked' inspect method failed

[W 190409 17:22:45 control:44] 'conf' inspect method failed

**Comment by tikazyq** [comment]
影不影响运行？看得到节点在界面上吗

**Comment by cheneystar** [comment]
界面上无法看到节点

**Comment by cheneystar** [comment]
界面上无法看到节点

**Comment by tikazyq** [comment]
在啥环境下执行的？

**Comment by tikazyq** [comment]
已升级到v0.3.0，移除flower
