### ISSUE TITLE
执行python3 ./bin/run_worker.py

### ISSUE THREAD

**Issue by cheneystar** [tikazyq/crawlab#17]
python3 ./bin/run_worker.py
Traceback (most recent call last):
  File "./bin/run_worker.py", line 9, in <module>
    from tasks.celery import celery_app
ModuleNotFoundError: No module named 'tasks.celery'

**Comment by tikazyq** [comment]
还存在这样的问题吗？

**Comment by tikazyq** [comment]
无法复现
