### ISSUE TITLE
mac 下deploy任务id日志目录不存在的时候不会自动创建，导致任务出错

### ISSUE THREAD

**Issue by guapier** [tikazyq/crawlab#2]
mac 下deploy任务id日志目录不存在的时候不会自动创建，导致任务出错

**Comment by tikazyq** [comment]
看看是否是权限原因？

**Comment by guapier** [comment]
@tikazyq 我特意换到桌面目录下还是会有这个问题，挺奇怪的

**Comment by tikazyq** [comment]
@guapier 无法复现，请保证`config.py`中的`PROJECT_LOGS_FOLDER`目录有写权限
