### ISSUE TITLE
部署后没有反应，前端页面也无提示消息

### ISSUE THREAD

**Issue by CrownDaisy** [tikazyq/crawlab#3]
![image](https://user-images.githubusercontent.com/34273906/54206247-e9750900-4512-11e9-987a-7bf6eccae76b.png)
Refresh也没有反应，前端页面也重启服务了，但是单独运行爬虫是有数据的，也能存入MongoDB中。
![image](https://user-images.githubusercontent.com/34273906/54206332-12959980-4513-11e9-9b11-3a86a8a5e996.png)

**Comment by tikazyq** [comment]
@CrownDaisy 用最新的版本试一下（我本地无法复现），另外我看到task_id没有传进来，这也不正常

**Comment by tikazyq** [comment]
用Ubuntu的时候复现了，deploy_all的时候因为unzip打包失败，进一步查看原因

**Comment by CrownDaisy** [comment]
> @CrownDaisy用最新的版本试一下（我本地无法复现），另外我看到TASK_ID没有传进来，这也不正常

我猜是因为手动启动的爬虫任务，所以不存在task。
