### ISSUE TITLE
接口跨域问题，出现localhost

### ISSUE THREAD

**Issue by lissh** [tikazyq/crawlab#30]
Error
vue.runtime.esm.js?2b0e:619 [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "pageNum"

found in

---> <GeneralTableView> at src/components/TableView/GeneralTableView.vue
       <ElTabPane>
         <ElTabs>
           <TaskDetail> at src/views/task/TaskDetail.vue
             <AppMain> at src/views/layout/components/AppMain.vue
               <Layout> at src/views/layout/Layout.vue
                 <App> at src/App.vue
                   <Root>

**Comment by tikazyq** [comment]
这看起来是两个问题，一个标题里的，一个描述里的

**Comment by tikazyq** [comment]
已经在 https://github.com/tikazyq/crawlab/commit/4b0875186865177739729e14746f440aa8081682 中修复了，如果在生产环境中，请更改`.env.production`的`VUE_APP_API_BASE_URL`环境变量，这个将作为前端的API请求地址
