### ISSUE TITLE
直接执行app.py启动app的时候定时任务执行两次任务

### ISSUE THREAD

**Issue by tikazyq** [tikazyq/crawlab#32]
如题，如果`python app.py`启动app的时候，新建一个定时任务，会执行两次爬虫任务

**Comment by Blue-Skie** [comment]
你可以把debug关掉试试

**Comment by tikazyq** [comment]
fixed in https://github.com/tikazyq/crawlab/commit/7ed9a1836b92a02972ca767ae4a47e306724beb4
