### ISSUE TITLE
部署时可以自定义部署到哪些节点吗？

### ISSUE THREAD

**Issue by zhouyihaocc** [tikazyq/crawlab#51]
在DEMO中没有看到自定义部署到哪些节点的选项，但在实际中不是所有的爬虫都需要部署到每一台机器上的。

**Comment by tikazyq** [comment]
好问题，但是celery貌似不支持指定运行在哪一个节点上，因此需要部署到所以机器，至少现在没有找到解决办法

**Comment by spidercamel** [comment]
> 好问题，但是celery貌似不支持指定运行在哪一个节点上，因此需要部署到所以机器，至少现在没有找到解决办法

作者您好呀，针对celery貌似不支持指定运行在哪一个节点上的问题如果能解决那此作品就很有竞争力，加油呀作者，希望有一天可以解决此问题

**Comment by spidercamel** [comment]
多节点自定义管理真的很重要

**Comment by yanguangtao** [comment]
用ansible吧

**Comment by tikazyq** [comment]
在 https://github.com/tikazyq/crawlab/releases/tag/v0.3.0 中已经改为自动部署了，所有爬虫文件将被同步到所有在线节点，不需要人工操作。Python版本已经改为Golang版本
