### ISSUE TITLE
在线节点数没有过滤离线的，定时任务没有再启服气的时候起来

### ISSUE THREAD

**Issue by lissh** [tikazyq/crawlab#56]
在线节点数没有过滤离线的，定时任务没有再启服气的时候起来...PS：能否创建个分支给我，git帐号lissh

**Comment by tikazyq** [comment]
这是两个问题吧：

1. 过滤在线节点数，这个比较简单，但还没开发，会vue的话直接fork修改吧
2. 定时任务这个问题是指重启服务器的时候定时任务不工作么？

你这边直接fork然后提pr吧，新建分支挺麻烦的

**Comment by tikazyq** [comment]
新版本 https://github.com/tikazyq/crawlab/releases/tag/v0.3.0 已解决
