### ISSUE TITLE
Cannot load celery.commands extension 'flower.command:FlowerCommand': ModuleNotFoundError("No module named 'flower.command'; 'flower' is not a package"

### ISSUE THREAD

**Issue by muzhenghua** [tikazyq/crawlab#57]
环境：阿里 centos7 python3.7
nohup python3 flower.py  
报错： 'stats' inspect method failed
         'active_queues' inspect method failed
        。。。。。
nohup python3 worker.py   
报错 ：
/usr/local/python3/lib/python3.7/site-packages/celery/utils/imports.py:167: UserWarning: Cannot load celery.commands extension 'flower.command:FlowerCommand': ModuleNotFoundError("No module named 'flower.command'; 'flower' is not a package")
  namespace, class_name, exc))
/usr/local/python3/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!
Please specify a different user using the --uid option.
User information: uid=0 euid=0 gid=0 egid=0

**Comment by muzhenghua** [comment]
能外部访问网站，但是节点和爬虫没有。

**Comment by tikazyq** [comment]
这个应该是warning，看看是不是redis连不上？

**Comment by spidercamel** [comment]
我也遇到这个问题， 临时解决方案 就是自己在终端手动执行 命令直接启动，不要用python 启动，
celery flower --broker=redis://127.0.0.1:6379/0

**Comment by tikazyq** [comment]
flower 在v0.3.0中取消了，fixed
