### ISSUE TITLE
定时任务有时不工作

### ISSUE THREAD

**Issue by tikazyq** [tikazyq/crawlab#64]
删除、更新、添加定时任务，定时任务并不正常工作

**Comment by spidercamel** [comment]
我这边测试也是 定时任务有问题， 不知道为什么apscheduler 任务add进去了，但是没有执行

**Comment by gnixuw** [comment]
很感谢tikazyq的分享。 #64 有修复计划吗？  感谢

**Comment by tikazyq** [comment]
@gnixuw 现在还没有复现出这个bug，等能稳定复现后再说吧，你如果遇到类似的问题也可以在这里说哈

**Comment by tikazyq** [comment]
fixed in v0.3.0
