### ISSUE TITLE
对于配置了username和password的MongoClient对象连接的MongoDB的时候：pymongo.errors.OperationFailure: auth failed

### ISSUE THREAD

**Issue by leegohi** [tikazyq/crawlab#68]
mongo=MongoClient(host=MONGO_HOST,
                                 port=MONGO_PORT,
                                 username=MONGO_USERNAME,
                                 password=MONGO_PASSWORD,
                                 authSource=MONGO_DB,
                                 connect=False)
对于上述初始化mongo对象的代码，需要在初始化MongoClient指定”authSource“字段为username这个账户对应有权限的数据库名称，否则会出现auth fail.具体原因：
一般我们设置MongoDB权限是针对某个db，auth也只能在这个db才能auth，否则就在admin那里auth，就会出现auth fail，对于MongoDB有权限控制的需要加这个 如果直接root账号密码 或者空账号密码那就不会出现我这个问题。

**Comment by tikazyq** [comment]
fixed in develop

**Comment by tikazyq** [comment]
need to configure `MONGO_AUTH_DB` in config.py
