### ISSUE TITLE
部署时出现问题 api出错

### ISSUE THREAD

**Issue by NameJaho** [tikazyq/crawlab#7]
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/spiders/5c9f2095428f2c217cc474e6/deploy_file?node_id=celery@26GXGQ2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000000096A3A20>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

**Comment by tikazyq** [comment]
默认端口设置韦8000
