### ISSUE TITLE
节点不会离线也无法删除

### ISSUE THREAD

**Issue by wo10378931** [tikazyq/crawlab#87]
![image](https://user-images.githubusercontent.com/8297691/62036419-5b30c380-b224-11e9-90b6-34519b2b045b.png)

使用k8s平台部署(deployment)，节点的IP使用service的ClusterIP，当对这个节点(master或者worker)进行更新，会发现在web平台看到2台节点，实际上有一台已经不存在了

**Comment by tikazyq** [comment]
这个是个已知bug，会在新版本（golang版本）v0.3.0解决的

**Comment by wo10378931** [comment]
阿，新版本，会把master的语言切换到golang ？

**Comment by wo10378931** [comment]
@tikazyq

**Comment by tikazyq** [comment]
@wo10378931 对的，是要切换的，计划本周晚些时候发布

**Comment by wo10378931** [comment]
期待。。
